install: true
script:
  - eval "$(ssh-agent -s)"
  - echo -e $BALENA_KEY > id_rsa
  - chmod 0600 id_rsa
  - ssh-add ./id_rsa
  - cat known_hosts >> ~/.ssh/known_hosts
  - git remote add balena "$BALENA_REMOTE"
  - git push -f balena $TRAVIS_BRANCH:master
